Repository 2024WISCOM/WISCOM-BE, pull requests merged in 2024-08, with the labels that each got.

#7 ✨[Feat] 방명록 작성 기능 구현 #6
  build.gradle
  src/main/java/com/wiscom/backend/controller/guestbookController.java
  src/main/java/com/wiscom/backend/dto/guestbook/guestbookDTO.java
  src/main/java/com/wiscom/backend/dto/response/ResponseDTO.java
  src/main/java/com/wiscom/backend/entity/guestbookEntity.java
  src/main/java/com/wiscom/backend/repository/guestbookRepository.java
  src/main/java/com/wiscom/backend/service/guestbookService.java
Labels: ✨ Feat

#8 ✨[FEAT] 작품 조회,상세 기능 구현 #5
  src/main/java/com/wiscom/backend/controller/WorksController.java
  src/main/java/com/wiscom/backend/dto/response/WorksDetailResponseDTO.java
  src/main/java/com/wiscom/backend/dto/response/WorksResponseDTO.java
  src/main/java/com/wiscom/backend/entity/WorksEntity.java
  src/main/java/com/wiscom/backend/repository/WorksRepository.java
  src/main/java/com/wiscom/backend/service/WorksService.java
Labels: ✨ Feat

#13 ✨[FEAT] 작품 필터링 기능 구현 #11
  src/main/java/com/wiscom/backend/controller/WorksController.java
  src/main/java/com/wiscom/backend/repository/WorksRepository.java
  src/main/java/com/wiscom/backend/service/WorksService.java
Labels: ✨ Feat

#15 ✨[FEAT] 개발자 조회 기능 구현 #14
  src/main/java/com/wiscom/backend/controller/DeveloperController.java
  src/main/java/com/wiscom/backend/dto/response/DeveloperDTO.java
  src/main/java/com/wiscom/backend/dto/response/DeveloperNameDTO.java
  src/main/java/com/wiscom/backend/dto/response/WorksDetailResponseDTO.java
  src/main/java/com/wiscom/backend/entity/DeveloperEntity.java
  src/main/java/com/wiscom/backend/entity/WorksEntity.java
  src/main/java/com/wiscom/backend/repository/DeveloperRepository.java
  src/main/java/com/wiscom/backend/service/DeveloperService.java
Labels: ✨ Feat

#17 [FEAT] 방명록 조회 기능 구현 #10
  build.gradle
  src/main/java/com/wiscom/backend/dto/guestbook/guestbookDTO.java
  src/main/java/com/wiscom/backend/dto/response/PaginationResponseDTO.java
  src/main/java/com/wiscom/backend/entity/guestbookEntity.java
  src/main/java/com/wiscom/backend/repository/guestbookRepository.java
  src/main/java/com/wiscom/backend/service/guestbookService.java
Labels: ✨ Feat, ♻️ Refactor

#20 ✨[FEAT] 작품 상세 이미지 조회 기능 구현 #12
  src/main/java/com/wiscom/backend/dto/response/ImageResponseDTO.java
  src/main/java/com/wiscom/backend/dto/response/WorksDetailResponseDTO.java
  src/main/java/com/wiscom/backend/entity/ImageEntity.java
  src/main/java/com/wiscom/backend/entity/WorksEntity.java
Labels: ✨ Feat

#28 ♻️ [REFACTOR] 테이블명 works_category에서 WorkCategory로 변경
  src/main/java/com/wiscom/backend/entity/WorksEntity.java
Labels: ♻️ Refactor
